default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432
  username: kech
  password: 1111

development:
  <<: *default
  database: kech_dev

test:
  <<: *default
  database: kech_test

production:
  <<: *default
  database: kech_prod
